- hosts: loadbalancer
  vars_prompt:
  - name: port_number
    private: no
    prompt: "Enter the port number for load balancer"
  tasks:
  - name: "Installing haproxy"
    package: 
      name: haproxy
      state: present

  - name: "Copying haproxy configuration file"
    template: 
       src: /ws5/haproxy.cfg.j2
       dest: /etc/haproxy/haproxy.cfg
    notify: Restarting haproxy

  - name: "Starting haproxy service"
    service:
        name: haproxy
        state: started


  handlers:
  - name: Restarting haproxy
    service:
        name: haproxy
        state: restarted   

  
