- hosts: loadbalancer
  vars_prompt:
  - name: port_number
    private: no
    prompt: "Enter the port number for load balancer"
  tasks:
  - name: "Creating Directory"
    file:
      state: directory
      path: /dvd

  - name: "Mounting DVD"
    mount:
         path: /dvd
         src: /dev/sr0
         fstype: iso9660
         opts: ro,noauto
         state: mounted
    ignore_errors: yes

  - name: "Configuring YUM repo"
    yum_repository:
         name: AppStream
         description: Repo for AppStream
         file: dvd.repo
         baseurl: file:///dvd/AppStream/
         gpgcheck: no

  - name: "Configuring Base YUM repo"
    yum_repository:
          name: BaseOS
          description: Repo for BaseOS
          file: dvd.repo
          baseurl: file:///dvd/BaseOS/
          gpgcheck: no

  - name: "Installing haproxy"
    package: 
      name: haproxy
      state: present

  - name: "Copying haproxy configuration file"
    template: 
       src: /ws5/haproxy.cfg.j2
       dest: /etc/haproxy/haproxy.cfg
    notify: Restarting haproxy

  - name: "Stopping Firewall on port {{port_number}}"
    firewalld:
        port: "{{port_number}}/tcp"
        zone: public
        permanent: true
        immediate: true
        state: enabled


  - name: "Making SElinux permissive"
    selinux:
       policy: targeted
       state: permissive

  - name: "Starting haproxy service"
    service:
        name: haproxy
        state: started


  handlers:
  - name: Restarting haproxy
    service:
        name: haproxy
        state: restarted   



- hosts: webserver
  vars_prompt:
  - name: new_port
    private: no 
    prompt: "Enter the Port number for httpd: "
 
  - name: httpd_dir
    private: no
    prompt: "Enter the root  directory name for httpd"

  tasks:
  - name: "Creating Directory"
    file:
      state: directory
      path: /dvd

  - name: "Mounting DVD"
    mount:
         path: /dvd
         src: /dev/sr0
         fstype: iso9660
         opts: ro,noauto
         state: mounted
    ignore_errors: yes

  - name: "Configuring YUM repo"
    yum_repository:
         name: AppStream
         description: Repo for AppStream
         file: dvd.repo
         baseurl: file:///dvd/AppStream/
         gpgcheck: no

  - name: "Configuring Base YUM repo"
    yum_repository:
          name: BaseOS
          description: Repo for BaseOS
          file: dvd.repo
          baseurl: file:///dvd/BaseOS/
          gpgcheck: no

  - name: "Installing httpd software"
    package:
        name: 
           - httpd
           - php 

  - name: "Root directory for httpd"
    file:
         name: "/var/www/{{ httpd_dir }}"
         state: directory
  - name: "Copying configuration file"
    template:
            src: /ws4/custom.conf
            dest: /etc/httpd/conf.d/
    notify: Restarting web service

  - name: "Copying web page"
    template: 
        src: "/ws5/m.php"
        dest: "/var/www/{{ httpd_dir }}/m.php"

  - name: "Starting web service"
    service:
        name: httpd
        state: started

  - name: "Stopping firewall"
    firewalld:
         port: "{{new_port}}/tcp"
         zone: public
         permanent: true
         immediate: true
         state: enabled

  handlers:
  - name: Restarting web service
    service:
       name: httpd
       state: restarted
